#! /bin/sh

export PATH=$PATH:$HOME/.local/bin:$HOME/kitty/kitty/launcher/

bspc monitor -d I II III

bspc config border_width         3
bspc config window_gap           5

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -a Guake:\* state=floating
bspc rule -a Google-chrome:\* state=floating desktop='^2' follow=on
bspc rule -a feh state=floating
bspc rule -a xdman-Main:\* state=floating
bspc rule -a Blueman-manager state=floating rectangle=553x302+1339+52
bspc rule -a Gimp desktop='^3' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer        true
bspc config pointer_follows_monitor      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
#bspc config focused_border_color "#ff79c6"
bspc config focused_border_color "#dfdfdf"
bspc config presel_feedback_color "#6272a4"

#polkit gnome
sh $HOME/polkit-gnome.sh


#feh
~/.fehbg &

#sh $HOME/power.sh

sh $HOME/.config/polybar/launch.sh

sh $HOME/picom.sh

pgrep -x sxhkd > /dev/null || sxhkd &
