#! /bin/sh

export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/sbin:/bin:$HOME/.local/bin

bspc monitor -d I II III

bspc config border_width         3
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -a Chromium:\* state=floating follow=on
bspc rule -a feh state=floating
bspc rule -a xdman-Main:\* state=floating
bspc rule -a Blueman-manager state=floating rectangle=553x302+1339+52
bspc rule -a Gimp desktop='^3' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer        true
bspc config pointer_follows_monitor      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

#feh
~/.fehbg &

pgrep -x sxhkd > /dev/null || sxhkd &
